# Generated by Django 5.2 on 2025-07-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrafficSegmentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("segment_id", models.IntegerField(db_index=True)),
                ("street", models.CharField(max_length=255)),
                ("direction", models.CharField(max_length=10)),
                ("from_street", models.CharField(max_length=255)),
                ("to_street", models.CharField(max_length=255)),
                ("length", models.FloatField()),
                (
                    "street_heading",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("start_longitude", models.FloatField()),
                ("start_latitude", models.FloatField()),
                ("end_longitude", models.FloatField()),
                ("end_latitude", models.FloatField()),
                ("current_speed", models.IntegerField(default=-1)),
                ("recorded_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "verbose_name": "Traffic Segment Data",
                "verbose_name_plural": "Traffic Segment Data",
            },
        ),
    ]
